name: GHCR Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: lowercase repository
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Run GHCR Cleanup Action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: false                # true = test, false = esegue davvero
          delete-untagged: true         # elimina SOLO le immagini senza tag
